# LAN - A
pc1[0]=A
pc2[0]=A
fw[0]=A


# DMZ - B
web[0]=B
dns[0]=B
fw[1]=B

# Gerenciamento - C
adm[0]=C
fw[2]=C

# Rede de Borda (FW-R0-Internet) - D
fw[3]=D
# Conecta ponto a ponto com FW
r0[0]=D
# Conecta o Roteador na Internet
r0[bridged]=true

